### ISSUE TITLE
Set up Shell for Software

### ISSUE THREAD

**Issue by tgao1337** [tgao1337/flexible-pomodoro-tree#14]
- [x] write setup.py
- [x] Add to pomodoro.py (basically foo.py) each function used
  - [x] Display
  - [x] LED Driver
  - [x] Buzzer
- [x] Call all functions in pomodoro.py in demo.py
  - [x] Display
  - [x] LED Driver
  - [x] Buzzer
- [x] Begin stub functions in pomodorotree.py (app.py)

**Comment by shahzebnaseer** [comment]
Looks good!
