### ISSUE TITLE
Write standards section of report

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#20]

**Comment by tgao1337** [comment]
need to fix shift register, i think i did that already.
double check before finalizing

**Comment by tgao1337** [comment]
https://docs.google.com/document/d/1uABwf7JZWQZij0Cscvf9MtQimIKzhypJEdI3mqXVhHU/edit#


![Image](https://user-images.githubusercontent.com/12534586/166724377-1b69df61-9387-4257-97f0-e556af7c83a1.png)

check the red parts
