### ISSUE TITLE
Pitch video

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#25]
- [x] Message box
- [x] Record the video
- [x] Submit to Capstone Competition

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/164129078-646cfa82-af26-4fab-a532-be4ad12f42b9.png)

@ffund can you review our message box? We addressed the previous feedback you have given us.

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/164584769-20284430-f730-48cc-af5f-e8f7e6a6002e.png)
