### ISSUE TITLE
LED and Driver Subsystem

### ISSUE THREAD

**Issue by tgao1337** [tgao1337/flexible-pomodoro-tree#28]
- [x] Check part liveness
  - [x] how does it connect, show pictures and schematics
  - [x] and show result
- [x] Fill in stub functions
  - [x] reference commit
  - [x] describe functions
  - [x] describe design decisions
  - [x] describe tests and result of test
- [x] Understand and explain part in more depth
  - [x] ex. curve of distance to voltage
  - [x] ex, sensitivity setting
  - [x] ex. use I2S or other protocol
  - [x] lots of more instructions
- [x] Project specific tests for functionality
  - [x] describe test and justify
  - [x] explain how to use it
  - [x] what are results of test

**Split into issues #34 , #38 , #39, #40**

**Comment by nickcoluccio** [comment]
closed all realted issues

**Comment by tgao1337** [comment]
good

**Comment by shahzebnaseer** [comment]
nice
