### ISSUE TITLE
Buzzer Subsystems - Background and other functions

### ISSUE THREAD

**Issue by tgao1337** [tgao1337/flexible-pomodoro-tree#32]
- [x] Understand and explain part in more depth
  - [x] safe connections
    - [x] test more resister combinations and see current draw and what each resistor does
  - [x] other types of driving circuits
  - [x] MIDI tones
    - [x] play different frequencies
  - [x] lots of more instructions

**Comment by tgao1337** [comment]
https://github.com/rb2468/tray-a-way/issues/59
Talked to Rachel about starting up pigiod from boot

**Comment by shahzebnaseer** [comment]
Good work!

**Comment by tgao1337** [comment]
[New Part - Buzzer - Tommy Gao (2).pdf](https://github.com/tgao1337/flexible-pomodoro-tree/files/8171682/New.Part.-.Buzzer.-.Tommy.Gao.2.pdf)
