### ISSUE TITLE
LED driver project related code and tests

### ISSUE THREAD

**Issue by nickcoluccio** [tgao1337/flexible-pomodoro-tree#39]
- [x] Project specific functions and tests for functionality 
  - [x] reference commit
  - [x] describe functions
  - [x] describe design decisions
  - [x] describe tests and result of test

Split from issue #28

**Comment by nickcoluccio** [comment]
I re opened this issue since I updated the code now since from last meeting you guys wanted to have control over every LED. I now have a dictionary in which each color group is the key and the value is an array of 1,0 whether the given LEDs are on or not. 
### Function Explanation (disregard above  comments  too much has changed)

- **toggleClusterColorGroup(int cluster, char color, bool turnOn)**
This function turns on a given red, yellow or green color group in a specified cluster. It updates the ledDict and displays the 
new output.

- **toggleNextLed(bool turnOn)**
If turnOn is true, this function will search through the ledDict for the first zero and then set this to a 1. It starts at the lowest driver( which will be lowest on the tree physically) and searches for the first off led and turns it on. 
Conversely, if turnOn is false, it will search through the ledDict for the first one and the set this to a 0. It will start with the fourth driver( which will be place highest on the tree physically) and searches for the highest on led and turns it off. 

- **allOn()**
This function turns on all the LEDs by creating a string of all 1 and passing to passToLEDs. 

- **clearAll() - the same**
This function turns off all LEDs using the common SRCLR that will be attached to every driver.

- **selectClusterOFF(int cluster)
This function turns off every color group for a given cluster. 

- **setup()   - (the same)**
This function sets all the desired pins as outputs. It also sets the RCLK and SRCLK low so that they are ready to pass inputs. It sets SRCLR high so that the outputs do not get cleared.

_**The rest of these functions are not meant to be called by us and merely support the background updating of the ledDict or called by other higher level functions**_

- **updateClusterStatus(int cluster, bool turnOnWholeCluster, char color, bool turnOnLed)**
This function is called to update the dictionary. It finds the given key based on the arguments and updates the values in the array accordingly. There is the option to call any LED to turn it on or off from here, but the intention is that we would only need to update the above functions.

- **findNextLedToUpdateOn(key= "x" ) **
This is a recursive function which finds the first (lowest) led in the chain that is turned off. It then turns it on, updates the dict and allows the toggleNextLed() to display the new update. It starts the search at led driver 1 and red. 

- **findNextLedToUpdateOff(key="x")**
This is a recursive function which finds the first (highest) led in the chain that is turned on. It then turns it off, updates the dict and allows the toggleNextLed() to display the new update. It starts the search at led driver 4, green and works its way down. 

- **passToLEDs() - the same**
This function gets passed a 8 bit binary string and sends it along to the serial input where the SRCLK will pulse it in accordingly and RCLK willl pulse and display the sequence.

- **readClusterStatus(int cluster)**
Given a int cluster number, this function reads the dictinoary and generates a reversed 8 bit binary string to be passed to passToLEDs so that the current state of the cluster can be displayed. 

- **display() - the same **
Pulses RCLK to display what is stored in the registers.

**Comment by tgao1337** [comment]
This looks good

**Comment by shahzebnaseer** [comment]
Good work!
