### ISSUE TITLE
LED driver background/ deeper understanding 

### ISSUE THREAD

**Issue by nickcoluccio** [tgao1337/flexible-pomodoro-tree#40]
- [ ] Understand and explain part in more depth
  - [ ] ex. individual LEDs!
  - [ ] ex, patterns 
  - [ ] lots of more instructions

Split from issues #28

**Comment by nickcoluccio** [comment]
**RCLK vs SRCLK**

- there are two registers in the led driver. each clock controls each register to pass data in. 
- SRCLK shifts serial data amongst the outputs. RCLK shifts the data to the output.
- You can  pulse each input to output by pulsing SRCLK and then RCLK or you can pass in an entire 
driver's data using SRCLK and then pulsing RCLK once at the end. 

**Timing**

- There are various timing requirements to hold pulses so that the driver can driver can register the change. These timing requirements are very small (less than 150 ns). 
- You can increase the speed of leds by lowering the delay between the pulsing of clocks
- According to datasheet, if you use higher Vcc, you decrease the minimum timing requirements for all pulses. 

**SPI**

- You can treat the led driver as an SPI device, using SPI pins to pass entire bytes of data to the serial input.

**Comment by tgao1337** [comment]
Looks good

**Comment by shahzebnaseer** [comment]
Good work!
