### ISSUE TITLE
Compile user research for personas

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#42]

**Comment by shahzebnaseer** [comment]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/78505233/157494188-f946b958-402e-43a7-9aa2-cd4bb75456ce.png">

**Comment by nickcoluccio** [comment]
We split up our user stories into three general groups. Some stories that do not fall in any of these groups were left in red. 
- All of the stories that are orange have to do with the flexibility of a given productivity  method. People complained about or enjoyed following a specific time regimen. 
- The yellow group is for stories that talked about how users get distracted or forget to use a given productivity method.
- The blue group is for stories that highlighted people's difficulties with using an overcomplicated method and their preferences regarding how it would have been more easy to grasp.

**Comment by tgao1337** [comment]
This may be added or changed if anything is required for #44 and #43

**Comment by tgao1337** [comment]
Thanks Nick for additional stories.
