### ISSUE TITLE
Create affinity map

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#43]

**Comment by shahzebnaseer** [comment]
Looks good!

**Comment by tgao1337** [comment]
^ #44 not 43 sorry

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/160755663-d270c8a1-49fa-45bb-a5e6-0109568625dd.png)

**Comment by shahzebnaseer** [comment]
@ffund We have updated our affinity map and personas (issue #44). Could you please review them?

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/163097238-8068782c-27ca-4265-91bb-a9e46366923f.png)
