### ISSUE TITLE
Create personas

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#44]

**Comment by shahzebnaseer** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/78505233/157503894-a158197a-b1df-4d1a-9038-f629be2f43e3.png">

**Comment by nickcoluccio** [comment]
![image](https://user-images.githubusercontent.com/72901664/157504395-0de9cc12-62d1-474d-869e-809e81a27a59.png)

**Comment by shahzebnaseer** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/78505233/157504473-cd6edb30-bbad-4e77-8563-12307e9dbe47.png">

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/157504530-e1fab9fb-c37e-4d9f-bbda-28b09464013d.png)

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/157504586-06943661-4a55-4ef0-a1c1-616aa5727ef3.png)

**Comment by tgao1337** [comment]
@ffund Can you review our personas please?

**Comment by ffund** [comment]
@tgao1337 where can I find the affinity map that was used to create these?

**Comment by tgao1337** [comment]
@ffund Apologies, it is in #43

**Comment by ffund** [comment]
@tgao1337 I have too many comments on this and #43 to write out here, let's discuss in the next lab session.

**Comment by tgao1337** [comment]
see #44

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/160755963-5d02084f-318a-4856-8f08-f92e2c699cf8.png)
![image](https://user-images.githubusercontent.com/12534586/160755976-a0d31469-efc6-4723-9e90-5427d6c474f6.png)
![image](https://user-images.githubusercontent.com/12534586/160755988-1716b953-4f80-4a8f-9465-f82d82d21d69.png)
![image](https://user-images.githubusercontent.com/12534586/160756017-60071ea7-7cd1-43ae-9495-556993285478.png)
![image](https://user-images.githubusercontent.com/12534586/160756029-3e651aae-0f32-4d89-800f-a107242e81f1.png)

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/163097273-1e43d271-d335-40e1-8087-f922e34e208f.png)
![image](https://user-images.githubusercontent.com/12534586/163097288-4b7f0f5c-6719-4d3b-b04c-dc12eb1a3a9c.png)
![image](https://user-images.githubusercontent.com/12534586/163097298-7296aa25-a8d1-427d-8616-41abe0cd4da7.png)
![image](https://user-images.githubusercontent.com/12534586/163097307-a5e4d737-2f3b-4165-8a00-665c80d4eed5.png)

**Comment by ffund** [comment]
These look good!
