### ISSUE TITLE
Wireframe for physical product UI

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#47]

**Comment by shahzebnaseer** [comment]
We started working on the wireframe for the physical product UI. I have attached the basic design and we will be making changes as we progress through the issues #43 and #44.

[Flexible Pomodoro Tree Physical Wireframe.pdf](https://github.com/tgao1337/flexible-pomodoro-tree/files/8334930/Flexible.Pomodoro.Tree.Physical.Wireframe.pdf)

**Comment by tgao1337** [comment]
Let us reconsider the buttons. There may be a lot of buttons and some functionality can overlap.

**Comment by tgao1337** [comment]
Update the wireframe so when you click different buttons, it shows a different mode screen. Also decide if we should keep all the buttons or have one button that cycles in different modes.

**Comment by shahzebnaseer** [comment]
Updated Physical UI:
[Flexible Pomodoro Tree Wireframe.pdf](https://github.com/tgao1337/flexible-pomodoro-tree/files/8414481/Flexible.Pomodoro.Tree.Wireframe.pdf)
