### ISSUE TITLE
Review wireframes WRT personas

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#49]

**Comment by tgao1337** [comment]
Having a default user experience upon startup is great for someone who wants to begin their work early such as Andrea and Nia.

The system will be simple that it is not too distracting for users like Alex and Harvey but still accomplish the goal of staying productive.

The display will show what mode the user is in and additional information about the session which will make it easy to understand for the user the state they are in.

Having three modes changeable by cycling with one button will be good for Nia or Andrea to start a productive session on the fly without any hassles. The modes will also address different needs for users such as Harvey or Alex.

Additional settings can be configured using the same buttons so it is more customizable for users such as Alex.

The LEDs will help users such as Alex show off his productivity or for Andrea's kids to feel proud to accomplish something. The flexibility of this device is intended to address different situations to best help the user for different tasks.
