### ISSUE TITLE
Application Layer 

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#54]
- [x] Write functions for one-time tasks and call them in main
- [x] Fill in the empty functions from #51
- [x] Create threads for background tasks
- [x] Write functions that run in response to to something.

**Comment by tgao1337** [comment]
add
`global pomoStartTime
global pomoEndTime
pomoStartTime = time.time()
pomoEndTime = pomoStartTime + pomoWorkTime`

**Comment by tgao1337** [comment]
This is pretty much done. See pomodorotree_v2.py
