### ISSUE TITLE
Design PCB board on KiCad

### ISSUE THREAD

**Issue by nickcoluccio** [tgao1337/flexible-pomodoro-tree#56]
Based on footprints and schematic, design the PCB board. 
- [x] Schematic for Button Subsystem
- [x] Schematic for Display Subsystem
- [x] Schematic for Buzzer Subsystem
- [x] Schematic for LED Subsystem
- [x] Design PCB

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/164141008-8f8be5d0-7f14-4adb-be1f-a75c3ede28ff.png)

Began working on schematic with @shahzebnaseer

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/164150352-c008ac68-4d50-4d49-ab70-e498ed43b1af.png)

@nickcoluccio please check the led driver. We marked QH' as disconnected for the last daisy chain because it was giving an error in the ERC and that fixed it.

**Comment by tgao1337** [comment]
The pcb still needs to be designed

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/166399256-9b2cd6c9-ec66-4c70-a2a5-2ce5db9ebba5.png)
See this for #55 too. This is the updated schematic with 5 buttons instead of 6 and LED driver with GPIO 18 pin instead of  8

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/166411761-c5372960-f8f4-4af5-8703-88311b97d1c7.png)
added 4 more leds for total 32 leds

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/166413117-bd7540cb-a17d-4f9c-9cb6-74308c836274.png)

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/166413173-3be24d2b-537b-4538-ae8a-0c3dc6438f16.png)

**Comment by tgao1337** [comment]
[pomodoro.zip](https://github.com/tgao1337/flexible-pomodoro-tree/files/8608647/pomodoro.zip)
Here is the project files at this stage in the PCB design. We need to add traces and move things around if they don't work.

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/166623004-e97a2b93-7724-4560-a2d4-fa5e35516cfe.png)
still a work in progress
[pomodoro.zip](https://github.com/tgao1337/flexible-pomodoro-tree/files/8617864/pomodoro.zip)

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/167462317-d30d9fb3-fff0-4f14-928a-c129c508db8d.png)
![image](https://user-images.githubusercontent.com/12534586/167462335-7eb4bca0-238d-4185-8f2c-7e95f2f2a8e9.png)

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/167462779-c8be37e5-14fd-4302-8932-5db1f27dd0fe.png)

Front: 
![image](https://user-images.githubusercontent.com/12534586/167462862-796e9f04-ba8d-4edf-9fd7-d850cc8bca50.png)

Back:
![image](https://user-images.githubusercontent.com/12534586/167462963-ef357499-5339-46fc-9e9f-3a6ad9d6fc1b.png)

**Comment by tgao1337** [comment]
![image](https://user-images.githubusercontent.com/12534586/167531627-4cb635ae-993a-4c5d-976c-2c996027b787.png)

![image](https://user-images.githubusercontent.com/12534586/167531906-f4cd624d-303e-49d1-abc1-74c11503575f.png)
![image](https://user-images.githubusercontent.com/12534586/167531961-67d3b1bb-5f86-4d31-a6b7-87483fa0ed5f.png)

![image](https://user-images.githubusercontent.com/12534586/167532144-0a34b025-32fd-46b2-ad34-9acac53d2015.png)


Front:
![image](https://user-images.githubusercontent.com/12534586/167532043-fe2be8b3-c55b-4443-a7ce-33bafa15653a.png)
Back:
![image](https://user-images.githubusercontent.com/12534586/167532117-fc3754cd-d039-4a63-826d-453b1b62fc57.png)

**Comment by tgao1337** [comment]
updated

**Comment by tgao1337** [comment]
[pomodoro.zip](https://github.com/tgao1337/flexible-pomodoro-tree/files/8657251/pomodoro.zip)
