### ISSUE TITLE
Perfboard layout planning 

### ISSUE THREAD

**Issue by nickcoluccio** [tgao1337/flexible-pomodoro-tree#57]
Based on the schematic from the PCB, design the layout of the final components on the perfboard practice sheet.

**Comment by tgao1337** [comment]
<img width="1418" alt="pomoTreePerfDone" src="https://user-images.githubusercontent.com/12534586/166410926-e5455b41-7091-41c9-973b-7ec245b70d8f.png">

**Comment by shahzebnaseer** [comment]
good work!

**Comment by tgao1337** [comment]
<img width="1418" alt="pomoTreePerf" src="https://user-images.githubusercontent.com/12534586/167317720-63f73eeb-5299-470e-bc55-8a88fa02b601.png">
updated with buzzer
